### PR TITLE
HDF5Writer cleanup.

### PR DESCRIPTION
**Pull request by gbalduzz**
- Cleanup of the writer class, relying only on the C++ API.
- Keep datasets and group open, allowing to rewrite datasets and reaccessing the same group
- Cleanup writing of vectors and matrices. (easier to read from hdfview).

TODO:
- ~cleanup reader class as well.~

### CODE REVIEW

**Comment by gbalduzz** [comment]
retest this, please.

**Comment by PDoakORNL** [comment]
I am getting
```
terminate called after throwing an instance of 'H5::DataSpaceIException'
```
On my x86-64 test environment.  Any insight into this @gbalduzz

**Comment by PDoakORNL** [comment]
version 1.10.5

**Comment by gbalduzz** [comment]
Intersesting. I am using 1.10.4 and have seen no probelem either on my laptop, summit or daint. Which test is failing?

**Pull request merged**
