### PR TITLE
Tweak accum memory2

### PR DESCRIPTION
**Pull request by gbalduzz**
Follow up on #74.
Recycle the same memory allocation for intermediate results in the tp accumulation. It is implemented by using shared pointers to GPU matrices in each object performing a step of the accumulation.

### CODE REVIEW

**Comment by gbalduzz** [comment]
retest this, please.

**Comment by gbalduzz** [comment]
retest this, please.

**Comment by PDoakORNL** [comment]
Initially I see no test for reshapable matrix?  Tried dropping it into the matrix tests but you have not implemented much of that api.  Since you are using it as a drop in replacement for matrix one might assume at least that. Some calls such as capacity do not carry the same meaning they do for matrix. This is an important class it needs thorough tests.

**Comment by gbalduzz** [comment]
ReshapableMatrix tested in 4245407cc1adaf1cec18f4d77ea6febcb15c2923.

**Pull request merged**
