### PR TITLE
CT-INT

### PR DESCRIPTION
**Pull request by gbalduzz**
Trigger tests for CT-INT with no double vertex update.

Merge roadmap:
- ~Configuration~
- ~Accumulator~
- ~G0 interpolation~
- ~D Matrix builder (write G0 elements from configuration and interpolation object)~
- ~~Walker (split in CPU, sumbmattrix CPU, submatrix GPU): depends on configuration updates.~~
- ~~Solver~~

### CODE REVIEW

**Comment by gbalduzz** [comment]
retest this, please.

**Comment by gbalduzz** [comment]
retest this, please.

**Comment by gbalduzz** [comment]
retest this, please.

**Comment by gbalduzz** [comment]
retest this, please.

**Comment by gbalduzz** [comment]
retest this, pease

**Comment by gbalduzz** [comment]
retest this, please

**Comment by gbalduzz** [comment]
retest this, please

**Comment by gbalduzz** [comment]
retest this, please.

**Comment by gbalduzz** [comment]
retest this, please

**Comment by gbalduzz** [comment]
retest this, please.

**Comment by gbalduzz** [comment]
retest this, please.

**Comment by PDoakORNL** [comment]
The contents of this draft have been merged.

**Pull request closed without merging**
