### PR TITLE
Tweak accumulator memory.

### PR DESCRIPTION
**Pull request by gbalduzz**
First round of improvements in the accumulator's memory consumption.

* Allow Matrix and Vector to use custom allocators. Wrote each currently used allocator in a separate class.
* Define a new cmake option `DCA_WITH_MEMORY_SAVINGS` to compute sequentially the two spin sectors during the tp accumulation. This uses less memory for the intermediate results.

Depends on #62.

### CODE REVIEW

**Comment by gbalduzz** [comment]
retest this please.

**Comment by gbalduzz** [comment]
retest this please.

**Comment by gbalduzz** [comment]
retest this, please.

**Comment by PDoakORNL** [comment]
retest this please

**Comment by gbalduzz** [comment]
retest this, please.

**Pull request merged**
