### PR TITLE
Clean up StdthreadQmciClusterSolver.

### PR DESCRIPTION
**Pull request by gbalduzz**
Updated the coding style of the threaded solver interface. No effective changes.

### CODE REVIEW

**Comment by gbalduzz** [comment]
retest this, please.

**Comment by gbalduzz** [comment]
In the coding standard we just have that type names must be upper case. We don't really have a convention for template parameters, and we often have to store them in a class. Maybe something like 
```
template <class  Arg_> 
class Foo {
 using Arg = Arg_
};
```
?

**Comment by PDoakORNL** [comment]
This template parameter naming issue is a little more subtle than I thought. We have frequent cases of subtypes accessing types that are there supertypes template parameters. This asks more of the naming than you might think initially and are why we have Parameters, ParametersType, parameters_type etc. in the code. I think I have something sorted out but I want to see it work to clean up this sort of inconsistency across the code before I propose it.

Certainly this PR is not the place to solve it.

**Comment by uhaehner** [comment]
For me template parameters are just types. So the naming convention for types should apply.
But I'm not against bringing in some consistency when a template parameter is exposed again via a typedef.

**Pull request merged**
