### PR TITLE
Replace/remove deprecated four-point parameter 'type'

### PR DESCRIPTION
**Pull request by uhaehner**
Addresses https://github.com/CompFUSE/DCA-develop/issues/225 and #124.

The wiki has been updated.

@PDoakORNL Do we want to create a minor release for this?

### CODE REVIEW

**Comment by gbalduzz** [comment]
If we want to maintain backward compatibility of input files, would it not be better to remove four_point_type_ from the parameters, try to read "four-point-type" from the input, and set the appropriate channel flag to true?

**Comment by uhaehner** [comment]
Yes, the intention was backward compatibility and I agree that four-point-type should disappear entirely in the code.
However, I've just figured that this would lead to rather invasive changes from tp-coarsegraining to the ED solver, to the BSE solver.
Since I cannot implement all of these changes now, I propose that we roll back to the old interface while keeping multiple G4 channels under the hood in DcaData and TpAccumulator.

**Comment by PDoakORNL** [comment]
@uhaehner I have no objections to this.

**Comment by uhaehner** [comment]
The wiki page is reverted and updated with the two new channels.
Closing this for now.

**Pull request closed without merging**
