### PR TITLE
Fix #94

### LINKED ISSUE #94: TpAccumulator: RDmn used instead of KDmn to invert momentum space vector
In the TpAccumulator class RDmn is used instead of KDmn to invert a momentum space vector k.
See:
https://github.com/CompFUSE/DCA/blob/master/include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/tp_accumulator.hpp#L315
https://github.com/CompFUSE/DCA/blob/master/include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/tp_accumulator.hpp#L316
https://github.com/CompFUSE/DCA/blob/master/include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/tp_accumulator.hpp#L336
https://github.com/CompFUSE/DCA/blob/master/include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/tp_accumulator.hpp#L337

### PR DESCRIPTION
**Pull request by gbalduzz**
As per title.

### CODE REVIEW

**Comment by uhaehner** [comment]
Test that shows the bug?

**Comment by gbalduzz** [comment]
R and K domain have the same indexing most of the times (definitely for square lattices), hence the tests were already passing. I would just merge it.

**Comment by uhaehner** [comment]
Yeah, I didn't mean a test that passes but a test that fails because of the bug.
Also, e.g. for the square lattice [-2, 0], [0, 2], the indexing of R and K domain is different.

**Comment by gbalduzz** [comment]
It is clearly a typo that got past the review in an underutilized branch of the code (the CPU accumulation). I don't think there is anything useful in spending time testing that a code with a typo fails in certain specific scenarios.

**Pull request merged**
